name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend_react/**'  # Runs only if frontend code changes

env:
  DOCKER_FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/lms-frontend
  REACT_APP_API_URL: http://${{ secrets.SERVER_IP }}

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend_react
          platforms: linux/amd64,linux/arm64
          push: true
          no-cache: true
          build-args: |
            REACT_APP_API_URL=${{ env.REACT_APP_API_URL }}
          tags: |
            ${{ env.DOCKER_FRONTEND_IMAGE }}:2.0.0
            ${{ env.DOCKER_FRONTEND_IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKER_FRONTEND_IMAGE }}:2.0.0
          cache-to: type=inline

  deploy-frontend:
    needs: build-and-push-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy frontend to server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          echo "Stopping frontend container..."
          docker-compose stop frontend
          echo "Removing old frontend image..."
          docker system prune -af
          echo "Pulling new frontend image..."
          docker-compose pull frontend
          echo "Restarting frontend container..."
          docker-compose up -d --force-recreate frontend
          echo "Frontend deployment complete!"
          EOF
